# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://db:5432/scrum_tasks
spring.datasource.username=postgres
spring.datasource.password=postgres

# Configuración de JPA y Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Opción para desactivar la creación de conexiones al realizar la carga de la vista en Spring (si lo deseas)
spring.jpa.open-in-view=false
